// NCrash.asm

// This file contains file inclusions, action edits, and assembly for Polygon Crash Bandicoot.

scope NCrash {

    // Modify Action Parameters             // Action                       // Animation                    // Moveset Data             // Flags
    Character.edit_action_parameters(NCRASH, Action.DeadU,                   File.CRASH_TUMBLE,              Crash.DMG_1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ScreenKO,                File.CRASH_TUMBLE,              Crash.DMG_1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Entry,                   File.CRASH_IDLE,                Crash.IDLE,                       -1)
    Character.edit_action_parameters(NCRASH, 0x006,                          File.CRASH_IDLE,                Crash.IDLE,                       -1)
    Character.edit_action_parameters(NCRASH, Action.Revive1,                 File.CRASH_DOWN_BOUNCE_D,       -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Revive2,                 File.CRASH_DOWN_STAND_D,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ReviveWait,              File.CRASH_IDLE,                Crash.IDLE,                       -1)
    Character.edit_action_parameters(NCRASH, Action.Idle,                    File.CRASH_IDLE,                Crash.IDLE,                       -1)
    Character.edit_action_parameters(NCRASH, Action.Walk1,                   File.CRASH_WALK1,               -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Walk2,                   File.CRASH_WALK2,               Crash.WALK,                       -1)
    Character.edit_action_parameters(NCRASH, Action.Walk3,                   File.CRASH_WALK3,               Crash.WALK,                       -1)
    Character.edit_action_parameters(NCRASH, 0x00E,                          File.CRASH_WALK_END,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Dash,                    File.CRASH_DASH,                Crash.DASH,                       -1)
    Character.edit_action_parameters(NCRASH, Action.Run,                     File.CRASH_RUN,                 Crash.RUN,                        -1)
    Character.edit_action_parameters(NCRASH, Action.RunBrake,                File.CRASH_RUN_BRAKE,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Turn,                    File.CRASH_TURN,                -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.TurnRun,                 File.CRASH_TURN_RUN,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.JumpSquat,               File.CRASH_LANDING,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ShieldJumpSquat,         File.CRASH_LANDING,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.JumpF,                   File.CRASH_JUMP_F,              Crash.JUMP,                       -1)
    Character.edit_action_parameters(NCRASH, Action.JumpB,                   File.CRASH_JUMP_B,              Crash.JUMP,                       -1)
    Character.edit_action_parameters(NCRASH, Action.JumpAerialF,             File.CRASH_JUMP_AERIAL_F,       Crash.JUMPA,                      -1)
    Character.edit_action_parameters(NCRASH, Action.JumpAerialB,             File.CRASH_JUMP_AERIAL_B,       Crash.JUMPA,                      -1)
    Character.edit_action_parameters(NCRASH, Action.Fall,                    File.CRASH_FALL,                -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.FallAerial,              File.CRASH_FALL_AERIAL,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Crouch,                  File.CRASH_CROUCH,              -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CrouchIdle,              File.CRASH_CROUCH_IDLE,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CrouchEnd,               File.CRASH_CROUCH_END,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.LandingLight,            File.CRASH_LANDING,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.LandingHeavy,            File.CRASH_LANDING,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Pass,                    File.CRASH_SHIELD_DROP,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ShieldDrop,              File.CRASH_SHIELD_DROP,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Teeter,                  File.CRASH_TEETER,              -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.TeeterStart,             File.CRASH_TEETER_START,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.DamageHigh1,             File.CRASH_DAMAGE_HIGH1,        Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageHigh2,             File.CRASH_DAMAGE_HIGH2,        Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageHigh3,             File.CRASH_DAMAGE_HIGH3,        Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageMid1,              File.CRASH_DAMAGE_MID1,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageMid2,              File.CRASH_DAMAGE_MID2,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageMid3,              File.CRASH_DAMAGE_MID3,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageLow1,              File.CRASH_DAMAGE_LOW1,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageLow2,              File.CRASH_DAMAGE_LOW2,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageLow3,              File.CRASH_DAMAGE_LOW3,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageAir1,              File.CRASH_DAMAGE_AIR1,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageAir2,              File.CRASH_DAMAGE_AIR2,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageAir3,              File.CRASH_DAMAGE_AIR3,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageElec1,             File.CRASH_DAMAGE_ELEC,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageElec2,             File.CRASH_DAMAGE_ELEC,         Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageFlyHigh,           File.CRASH_DAMAGE_FLY_HIGH,     Crash.DMG_2,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageFlyMid,            File.CRASH_DAMAGE_FLY_MID,      Crash.DMG_2,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageFlyLow,            File.CRASH_DAMAGE_FLY_LOW,      Crash.DMG_2,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageFlyTop,            File.CRASH_DAMAGE_FLY_TOP,      Crash.DMG_2,                      -1)
    Character.edit_action_parameters(NCRASH, Action.DamageFlyRoll,           File.CRASH_DAMAGE_FLY_ROLL,     Crash.DMG_2,                      -1)
    Character.edit_action_parameters(NCRASH, Action.WallBounce,              File.CRASH_TUMBLE,              Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.Tumble,                  File.CRASH_TUMBLE,              Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.FallSpecial,             File.CRASH_FALL_SPECIAL,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.LandingSpecial,          File.CRASH_LANDING,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Tornado,                 File.CRASH_TUMBLE,              -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.EnterPipe,               File.CRASH_ENTER_PIPE,          Crash.PIPEENTER,                  -1)
    Character.edit_action_parameters(NCRASH, Action.ExitPipe,                File.CRASH_EXIT_PIPE,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ExitPipeWalk,            File.CRASH_EXIT_PIPE_WALK,      -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CeilingBonk,             File.CRASH_CEILING_BONK,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.DownBounceD,             File.CRASH_DOWN_BOUNCE_D,       Crash.DOWNBOUNCE,                 -1)
    Character.edit_action_parameters(NCRASH, Action.DownBounceU,             File.CRASH_DOWN_BOUNCE_U,       Crash.DOWNBOUNCE,                 -1)
    Character.edit_action_parameters(NCRASH, Action.DownStandD,              File.CRASH_DOWN_STAND_D,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.DownStandU,              File.CRASH_DOWN_STAND_U,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.TechF,                   File.CRASH_TECH_F,              Crash.TECH_ROLL,                  -1)
    Character.edit_action_parameters(NCRASH, Action.TechB,                   File.CRASH_TECH_B,              Crash.TECH_ROLL,                  -1)
    Character.edit_action_parameters(NCRASH, Action.DownForwardD,            File.CRASH_DOWN_FORWARD_D,      -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.DownForwardU,            File.CRASH_DOWN_FORWARD_U,      -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.DownBackD,               File.CRASH_DOWN_BACK_D,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.DownBackU,               File.CRASH_DOWN_BACK_U,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.DownAttackD,             File.CRASH_DOWN_ATK_D,          Crash.DOWNATTACK_D,               -1)
    Character.edit_action_parameters(NCRASH, Action.DownAttackU,             File.CRASH_DOWN_ATK_U,          Crash.DOWNATTACK_U,               -1)
    Character.edit_action_parameters(NCRASH, Action.Tech,                    File.CRASH_TECH,                Crash.TECH,                       -1)
    Character.edit_action_parameters(NCRASH, Action.ClangRecoil,             File.CRASH_CLANG_RECOIL,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffCatch,              File.CRASH_CLF_CATCH,           Crash.CLIFF_CATCH,                -1)
    Character.edit_action_parameters(NCRASH, Action.CliffWait,               File.CRASH_CLF_WAIT,            Crash.CLIFF_WAIT,                 -1)
    Character.edit_action_parameters(NCRASH, Action.CliffQuick,              File.CRASH_CLF_Q,               -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffClimbQuick1,        File.CRASH_CLF_CLM_Q1,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffClimbQuick2,        File.CRASH_CLF_CLM_Q2,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffSlow,               File.CRASH_CLF_S,               -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffClimbSlow1,         File.CRASH_CLF_CLM_S1,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffClimbSlow2,         File.CRASH_CLF_CLM_S2,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffAttackQuick1,       File.CRASH_CLF_ATK_Q1,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffAttackQuick2,       File.CRASH_CLF_ATK_Q2,          Crash.CLIFF_ATTACK_QUICK_2,       -1)
    Character.edit_action_parameters(NCRASH, Action.CliffAttackSlow1,        File.CRASH_CLF_ATK_S1,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffAttackSlow2,        File.CRASH_CLF_ATK_S2,          Crash.CLIFF_ATTACK_SLOW_2,        -1)
    Character.edit_action_parameters(NCRASH, Action.CliffEscapeQuick1,       File.CRASH_CLF_ESC_Q1,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffEscapeQuick2,       File.CRASH_CLF_ESC_Q2,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffEscapeSlow1,        File.CRASH_CLF_ESC_S1,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.CliffEscapeSlow2,        File.CRASH_CLF_ESC_S2,          Crash.CLIFF_ESCAPE_S2,            -1)
    Character.edit_action_parameters(NCRASH, Action.LightItemPickup,         File.CRASH_L_ITM_PICKUP,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.HeavyItemPickup,         File.CRASH_H_ITM_PICKUP,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemDrop,                File.CRASH_ITM_DROP,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowDash,           File.CRASH_ITM_THROW_DASH,      -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowF,              File.CRASH_ITM_THROW_F,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowB,              File.CRASH_ITM_THROW_F,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowU,              File.CRASH_ITM_THROW_U,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowD,              File.CRASH_ITM_THROW_D,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowSmashF,         File.CRASH_ITM_THROW_F,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowSmashB,         File.CRASH_ITM_THROW_F,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowSmashU,         File.CRASH_ITM_THROW_U,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowSmashD,         File.CRASH_ITM_THROW_D,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowAirF,           File.CRASH_ITM_THROW_AIR_F,     -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowAirB,           File.CRASH_ITM_THROW_AIR_F,     -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowAirU,           File.CRASH_ITM_THROW_AIR_U,     -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowAirD,           File.CRASH_ITM_THROW_AIR_D,     -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowAirSmashF,      File.CRASH_ITM_THROW_AIR_F,     -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowAirSmashB,      File.CRASH_ITM_THROW_AIR_F,     -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowAirSmashU,      File.CRASH_ITM_THROW_AIR_U,     -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ItemThrowAirSmashD,      File.CRASH_ITM_THROW_AIR_D,     -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.HeavyItemThrowF,         File.CRASH_H_ITM_THROW,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.HeavyItemThrowB,         File.CRASH_H_ITM_THROW,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.HeavyItemThrowSmashF,    File.CRASH_H_ITM_THROW,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.HeavyItemThrowSmashB,    File.CRASH_H_ITM_THROW,         -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.BeamSwordNeutral,        File.CRASH_ITM_JAB,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.BeamSwordTilt,           File.CRASH_ITM_TILT,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.BeamSwordSmash,          File.CRASH_ITM_SMASH,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.BeamSwordDash,           File.CRASH_ITM_DASH,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.BatNeutral,              File.CRASH_ITM_JAB,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.BatTilt,                 File.CRASH_ITM_TILT,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.BatSmash,                File.CRASH_ITM_SMASH,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.BatDash,                 File.CRASH_ITM_DASH,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.FanNeutral,              File.CRASH_ITM_JAB,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.FanTilt,                 File.CRASH_ITM_TILT,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.FanSmash,                File.CRASH_ITM_SMASH,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.FanDash,                 File.CRASH_ITM_DASH,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.StarRodNeutral,          File.CRASH_ITM_JAB,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.StarRodTilt,             File.CRASH_ITM_TILT,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.StarRodSmash,            File.CRASH_ITM_SMASH,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.StarRodDash,             File.CRASH_ITM_DASH,            -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.RayGunShoot,             File.CRASH_ITM_SHOOT,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.RayGunShootAir,          File.CRASH_ITM_SHOOT_AIR,       -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.FireFlowerShoot,         File.CRASH_ITM_SHOOT,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.FireFlowerShootAir,      File.CRASH_ITM_SHOOT_AIR,       -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.HammerIdle,              File.CRASH_HAMMER_IDLE,         Crash.HAMMER,                     -1)
    Character.edit_action_parameters(NCRASH, Action.HammerWalk,              File.CRASH_HAMMER_WALK,         Crash.HAMMER,                     -1)
    Character.edit_action_parameters(NCRASH, Action.HammerTurn,              File.CRASH_HAMMER_WALK,         Crash.HAMMER,                     -1)
    Character.edit_action_parameters(NCRASH, Action.HammerJumpSquat,         File.CRASH_HAMMER_WALK,         Crash.HAMMER,                     -1)
    Character.edit_action_parameters(NCRASH, Action.HammerAir,               File.CRASH_HAMMER_WALK,         Crash.HAMMER,                     -1)
    Character.edit_action_parameters(NCRASH, Action.HammerLanding,           File.CRASH_HAMMER_WALK,         Crash.HAMMER,                     -1)
    Character.edit_action_parameters(NCRASH, Action.ShieldOn,                File.CRASH_SHIELD_ON,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ShieldOff,               File.CRASH_SHIELD_OFF,          -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.RollF,                   File.CRASH_ROLL_F,              -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.RollB,                   File.CRASH_ROLL_B,              -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ShieldBreak,             File.CRASH_DAMAGE_FLY_TOP,      Crash.SHIELD_BREAK,               -1)
    Character.edit_action_parameters(NCRASH, Action.ShieldBreakFall,         File.CRASH_TUMBLE,              -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.StunLandD,               File.CRASH_DOWN_BOUNCE_D,       -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.StunLandU,               File.CRASH_DOWN_BOUNCE_U,       -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.StunStartD,              File.CRASH_DOWN_STAND_D,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.StunStartU,              File.CRASH_DOWN_STAND_U,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.Stun,                    File.CRASH_STUN,                Crash.STUN,                       -1)
    Character.edit_action_parameters(NCRASH, Action.Sleep,                   File.CRASH_STUN,                Crash.SLEEP,                      -1)
    Character.edit_action_parameters(NCRASH, Action.Grab,                    File.CRASH_GRAB,                Crash.GRAB,                       -1)
    Character.edit_action_parameters(NCRASH, Action.GrabPull,                File.CRASH_GRAB_PULL,           -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ThrowF,                  File.CRASH_THROW_F,             Crash.THROW_F,                    0x50000000)
    Character.edit_action_parameters(NCRASH, Action.ThrowB,                  File.CRASH_THROW_B,             Crash.THROW_B,                    -1)
    Character.edit_action_parameters(NCRASH, Action.CapturePulled,           File.CRASH_CAPTURE_PULLED,      Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.InhalePulled,            File.CRASH_TUMBLE,              Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.InhaleSpat,              File.CRASH_TUMBLE,              -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.InhaleCopied,            File.CRASH_TUMBLE,              -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.EggLayPulled,            File.CRASH_CAPTURE_PULLED,      Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.EggLay,                  File.CRASH_IDLE,                Crash.IDLE,                       -1)
    Character.edit_action_parameters(NCRASH, Action.FalconDivePulled,        File.CRASH_DAMAGE_HIGH3,        -1,                         -1)
    Character.edit_action_parameters(NCRASH, 0x0B4,                          File.CRASH_TUMBLE,              -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.ThrownDKPulled,          File.CRASH_THROWN_DK_PULLED,    Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.ThrownMarioBros,         File.CRASH_THROWN_MARIO_BROS,   Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.ThrownDK,                File.CRASH_THROWN_DK,           Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.Thrown1,                 File.CRASH_THROWN1,             Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.Thrown2,                 File.CRASH_THROWN2,             Crash.DMG_1,                      -1)
    Character.edit_action_parameters(NCRASH, Action.Taunt,                   File.CRASH_TAUNT,               Crash.TAUNT,                      0x10000000)
    Character.edit_action_parameters(NCRASH, Action.Jab1,                    File.CRASH_JAB1,                Crash.JAB,                        -1)
    Character.edit_action_parameters(NCRASH, Action.Jab2,                    0,                              0x80000000,                 0)
    Character.edit_action_parameters(NCRASH, Action.DashAttack,              File.CRASH_DASH_ATTACK,         Crash.DASH_ATTACK,                -1)
    Character.edit_action_parameters(NCRASH, Action.FTiltHigh,               File.CRASH_F_TILT_HIGH,         Crash.FTILT,                      -1)
    Character.edit_action_parameters(NCRASH, Action.FTilt,                   File.CRASH_F_TILT,              Crash.FTILT,                      -1)
    Character.edit_action_parameters(NCRASH, Action.FTiltLow,                File.CRASH_F_TILT_LOW,          Crash.FTILT,                      -1)
    Character.edit_action_parameters(NCRASH, Action.UTilt,                   File.CRASH_U_TILT,              Crash.UTILT,                      0)
    Character.edit_action_parameters(NCRASH, Action.DTilt,                   File.CRASH_D_TILT,              Crash.DTILT,                      0)
    Character.edit_action_parameters(NCRASH, Action.FSmashHigh,              0,                              0x80000000,                 0)
    Character.edit_action_parameters(NCRASH, Action.FSmashMidHigh,           0,                              0x80000000,                 0)
    Character.edit_action_parameters(NCRASH, Action.FSmash,                  File.CRASH_F_SMASH,             Crash.FSMASH,                     0x40000000)
    Character.edit_action_parameters(NCRASH, Action.FSmashMidLow,            0,                              0x80000000,                 0)
    Character.edit_action_parameters(NCRASH, Action.FSmashLow,               0,                              0x80000000,                 0)
    Character.edit_action_parameters(NCRASH, Action.USmash,                  File.CRASH_U_SMASH,             Crash.USMASH,                     -1)
    Character.edit_action_parameters(NCRASH, Action.DSmash,                  File.CRASH_D_SMASH,             Crash.DSMASH,                     -1)
    Character.edit_action_parameters(NCRASH, Action.AttackAirN,              File.CRASH_ATTACK_AIR_N,        Crash.ATTACK_AIR_N,               -1)
    Character.edit_action_parameters(NCRASH, Action.AttackAirF,              File.CRASH_ATTACK_AIR_F,        Crash.ATTACK_AIR_F,               -1)
    Character.edit_action_parameters(NCRASH, Action.AttackAirB,              File.CRASH_ATTACK_AIR_B,        Crash.ATTACK_AIR_B,               -1)
    Character.edit_action_parameters(NCRASH, Action.AttackAirU,              File.CRASH_ATTACK_AIR_U,        Crash.ATTACK_AIR_U,               -1)
    Character.edit_action_parameters(NCRASH, Action.AttackAirD,              File.CRASH_ATTACK_AIR_D,        Crash.ATTACK_AIR_D,               0)
    Character.edit_action_parameters(NCRASH, Action.LandingAirF,             File.CRASH_LANDING_AIR_F,       -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.LandingAirB,             File.CRASH_LANDING_AIR_B,       -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.LandingAirU,             File.CRASH_LANDING_AIR_U,       -1,                         -1)
    Character.edit_action_parameters(NCRASH, Action.LandingAirX,             File.CRASH_LANDING,             -1,                         -1)
    Character.edit_action_parameters(NCRASH, Crash.Action.Jab3,              0,                              0x80000000,                 0)
    Character.edit_action_parameters(NCRASH, Crash.Action.Entry_L,           File.CRASH_IDLE,                0x80000000,                 0)
    Character.edit_action_parameters(NCRASH, Crash.Action.Entry_R,           File.CRASH_IDLE,                0x80000000,                 0)
    // Character.edit_action_parameters(NCRASH, Crash.Action.NSPG,              File.CRASH_NSPG,                Crash.NSP,                        0)
    // Character.edit_action_parameters(NCRASH, Crash.Action.NSPA,              File.CRASH_NSPA,                Crash.NSP,                        0)
    // Character.edit_action_parameters(NCRASH, Crash.Action.NSPGBlocked,       File.CRASH_NSPG_BLOCKED,        Crash.NSP_BLOCKED,                0)
    // Character.edit_action_parameters(NCRASH, Crash.Action.NSPABlocked,       File.CRASH_NSPA_BLOCKED,        Crash.NSP_BLOCKED,                0)

    // Modify Actions               // Action           // Staling ID   // Main ASM                 // Interrupt/Other ASM      // Movement/Physics ASM         // Collision ASM
    Character.edit_action(NCRASH, Crash.Action.Entry_L, -1,             0x8013D994,                 0,                              0,                              0)
    Character.edit_action(NCRASH, Crash.Action.Entry_R, -1,             0x8013D994,                 0,                              0,                              0)
    //Character.edit_action(NCRASH,    Action.NSPG,        0x12,           CrashNSP.ground_main_,      0,                          CrashNSP.ground_physics_,       CrashNSP.ground_collision_)
    //Character.edit_action(NCRASH,    Action.NSPA,        0x12,           CrashNSP.air_main_,         0,                          CrashNSP.air_physics_,          CrashNSP.air_collision_)
    //Character.edit_action(NCRASH,    Action.NSPGBlocked, 0x12,           CrashNSP.blocked_main_,     0,                          0x800D8BB4,                     CrashNSP.blocked_ground_collision_)
    //Character.edit_action(NCRASH,    Action.NSPABlocked, 0x12,           CrashNSP.blocked_main_,     0,                          CrashNSP.blocked_air_physics_,  CrashNSP.blocked_air_collision_)
	//
    //// Add Action Parameters                // Action Name      // Base Action  // Animation                // Moveset Data             // Flags
    //Character.add_new_action_params(NCRASH,  DSPBegin,           -1,             File.CRASH_DSP_BEGIN,       Crash.DSP_BEGIN,                  0)
    //Character.add_new_action_params(NCRASH,  DSPWait,            -1,             File.CRASH_DSP_WAIT,        Crash.DSP,                        0)
    //Character.add_new_action_params(NCRASH,  DSPTurn,            -1,             File.CRASH_DSP_TURN,        Crash.DSP_TURN,                   0)
    //Character.add_new_action_params(NCRASH,  DSPEnd,             -1,             File.CRASH_DSP_ATTACK,      Crash.DSP_END,                    0)
    //Character.add_new_action_params(NCRASH,  DSPDive,            -1,             File.CRASH_DSP_PLATFORM,    Crash.DSP_DIVE,                   0)
    //Character.add_new_action_params(NCRASH,  DSPAirDive,         -1,             File.CRASH_DSP_AIR_DIVE,    Crash.DSP_DIVE,                   0)
    //Character.add_new_action_params(NCRASH,  USPG,               -1,             File.CRASH_USPG,            Crash.USP,                        0)
    //Character.add_new_action_params(NCRASH,  USPA,               -1,             File.CRASH_USPG,            Crash.USP,                        0)
    //Character.add_new_action_params(NCRASH,  USPLanding,         -1,             File.CRASH_USPLanding,      Crash.USP_LANDING,                0)
	//
    //// Add Actions                  // Action Name      // Base Action  //Parameters                    // Staling ID   // Main ASM                     // Interrupt/Other ASM          // Movement/Physics ASM             // Collision ASM
    //Character.add_new_action(NCRASH, DSPBegin,           -1,             ActionParams.DSPBegin,          0x1E,           CrashDSP.begin_main_,           0,                              0x800D8BB4,                         0x800DDF44)
    //Character.add_new_action(NCRASH, DSPWait,            -1,             ActionParams.DSPWait,           0x1E,           CrashDSP.wait_main_,            0,                              CrashDSP.physics_,                  CrashDSP.collision_)
    //Character.add_new_action(NCRASH, DSPTurn,            -1,             ActionParams.DSPTurn,           0x1E,           CrashDSP.turn_main_,            0,                              CrashDSP.physics_,                  CrashDSP.collision_)
    //Character.add_new_action(NCRASH, DSPEnd,             -1,             ActionParams.DSPEnd,            0x1E,           0x800D94E8,                     0,                              0x800D90E0,                         0x80156358)
    //Character.add_new_action(NCRASH, DSPDive,            -1,             ActionParams.DSPDive,           0x1E,           CrashDSP.dive_main_,            0,                              CrashDSP.dive_physics_,             CrashDSP.dive_collision_)
    //Character.add_new_action(NCRASH, DSPAirDive,         -1,             ActionParams.DSPAirDive,        0x1E,           CrashDSP.dive_main_,            0,                              CrashDSP.dive_air_physics_,         CrashDSP.dive_collision_)
    //Character.add_new_action(NCRASH, USPG,               -1,             ActionParams.USPG,              0x11,           CrashUSP.main_,                 CrashUSP.change_direction_,     CrashUSP.physics_,                  CrashUSP.collision_)
    //Character.add_new_action(NCRASH, USPA,               -1,             ActionParams.USPA,              0x11,           CrashUSP.main_,                 CrashUSP.change_direction_,     CrashUSP.physics_,                  CrashUSP.collision_)
    //Character.add_new_action(NCRASH, USPLanding,         -1,             ActionParams.USPLanding,        0x11,           0x800D94C4,                     0,                              0x800D8BB4,                         0x800DDEE8)


    // Modify Menu Action Parameters              // Action // Animation                // Moveset Data             // Flags
    Character.edit_menu_action_parameters(NCRASH,  0x0,      File.CRASH_IDLE,            Crash.IDLE,                       -1)
    Character.edit_menu_action_parameters(NCRASH,  0x1,      File.CRASH_VICTORY_1,       Crash.VICTORY1,                   -1)
    Character.edit_menu_action_parameters(NCRASH,  0x2,      File.CRASH_VICTORY_2,       Crash.VICTORY2,                   -1)
    Character.edit_menu_action_parameters(NCRASH,  0x3,      File.CRASH_VICTORY_3,       Crash.VICTORY3,                   0x10000000)
    Character.edit_menu_action_parameters(NCRASH,  0x4,      File.CRASH_CSS,             Crash.CSS,                        -1)
    Character.edit_menu_action_parameters(NCRASH,  0x5,      File.CRASH_CLAP,            Crash.CLAP,                       -1)
    Character.edit_menu_action_parameters(NCRASH,  0x9,      File.CRASH_CONTINUE_FALL,   -1,                         -1)
    Character.edit_menu_action_parameters(NCRASH,  0xA,      File.CRASH_CONTINUE_UP,     -1,                         -1)
    Character.edit_menu_action_parameters(NCRASH,  0xD,      File.CRASH_1P_POSE,         Crash.POSE_1P,                    -1)
    Character.edit_menu_action_parameters(NCRASH,  0xE,      File.CRASH_CPU_POSE,        -1,                         -1)

    Character.table_patch_start(ground_nsp, Character.id.NCRASH, 0x4)
    dw      CrashNSP.ground_initial_
    OS.patch_end()
    Character.table_patch_start(air_nsp, Character.id.NCRASH, 0x4)
    dw      CrashNSP.air_initial_
    OS.patch_end()
    Character.table_patch_start(ground_usp, Character.id.NCRASH, 0x4)
    dw      CrashUSP.ground_initial_
    OS.patch_end()
    Character.table_patch_start(air_usp, Character.id.NCRASH, 0x4)
    dw      CrashUSP.air_initial_
    OS.patch_end()
    Character.table_patch_start(ground_dsp, Character.id.NCRASH, 0x4)
    dw      CrashDSP.initial_
    OS.patch_end()
    Character.table_patch_start(air_dsp, Character.id.NCRASH, 0x4)
    dw      CrashDSP.dive_air_initial_
    OS.patch_end()

    // Set menu zoom size.
    Character.table_patch_start(menu_zoom, Character.id.NCRASH, 0x4)
    float32 1.1
    OS.patch_end()

    // Set action strings
    Character.table_patch_start(action_string, Character.id.NCRASH, 0x4)
    dw  Crash.Action.action_string_table
    OS.patch_end()

    // Allows Crash to use his entry which is based on Samus
    Character.table_patch_start(entry_action, Character.id.NCRASH, 0x8)
    dw Crash.Action.Entry_R, Crash.Action.Entry_R
    OS.patch_end()
    Character.table_patch_start(entry_script, Character.id.NCRASH, 0x4)
    dw 0x8013DCBC       // Samus's entry routine
    OS.patch_end()

    // Set Charge Smash attacks entry
    ChargeSmashAttacks.set_charged_smash_attacks(Character.id.NCRASH, Crash.charge_smash_frames)

    // Handles common things for Polygons
    Character.polygon_setup(NCRASH, CRASH)
}
